title: Royal Law X
description: Prosecuting organized white collar crime since 2022. \nContact at RoyalLawX@proton.me

# theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme