title: Royal Law
description: Prosecuting organized white collar crime since 2022. Contact RoyalLawX@pm.me

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

repository: RoyalLawX/royallawx.github.io